### ISSUE TITLE
getAllActs method in ActDao doesn't work properly

### ISSUE THREAD

**Issue by lukic-aleksandar** [srki/XMLCourseProject#5]
In this method ServerEvaluationCall object uses getAllActs xquery and adds variables like "text", "title" etc. but it doesn't add variables for "start_date" and "end_date", and that is why this method throws an exception. Fix this. I don't want to change your code.

**Comment by dimitrijejankov** [comment]
Commited a fix, please verify it's working,.

**Comment by dimitrijejankov** [comment]
Make sure to rerun the init/configure-db.sh and the data scripts.

**Comment by lukic-aleksandar** [comment]
fixed
